#define MAKI 128
#define VESI 64
#define KOYNNOS 32

#define KULMAKERROIN_PUOLI 0
#define KULMAKERROIN_YKSI 1
#define KULMAKERROIN_KAKSI 2
#define MIINUS 4
#define KATTO 8
#define ALAVAIHE 0
#define YLAVAIHE 16

#define VASEN_BLOKKI 1
#define YLA_BLOKKI 2
#define OIKEA_BLOKKI 4
#define ALA_BLOKKI 8

#define FYS_EI 0
#define FYS_MP 1
#define FYS_MAKI 2
#define FYS_KYYDISSA 3

const unsigned char tiletyyppitaulukko[] =
{
	0,
	VASEN_BLOKKI | YLA_BLOKKI,
	YLA_BLOKKI,
	OIKEA_BLOKKI | YLA_BLOKKI,
	VASEN_BLOKKI,
	OIKEA_BLOKKI,
	VASEN_BLOKKI | ALA_BLOKKI,
	ALA_BLOKKI,
	OIKEA_BLOKKI | ALA_BLOKKI,
	VASEN_BLOKKI | YLA_BLOKKI | OIKEA_BLOKKI | ALA_BLOKKI,
	MAKI | KULMAKERROIN_PUOLI | ALAVAIHE | MIINUS,
	MAKI | KULMAKERROIN_PUOLI | YLAVAIHE | MIINUS,

	MAKI | KULMAKERROIN_PUOLI | YLAVAIHE,
	MAKI | KULMAKERROIN_PUOLI | ALAVAIHE,
	
	MAKI | KULMAKERROIN_YKSI | YLAVAIHE | MIINUS,
	MAKI | KULMAKERROIN_YKSI | YLAVAIHE,

	MAKI | KULMAKERROIN_KAKSI | ALAVAIHE | MIINUS,
	MAKI | KULMAKERROIN_KAKSI | YLAVAIHE | MIINUS,

	MAKI | KULMAKERROIN_KAKSI | YLAVAIHE,
	MAKI | KULMAKERROIN_KAKSI | ALAVAIHE,

	MAKI | KATTO | KULMAKERROIN_PUOLI | YLAVAIHE ,
	MAKI | KATTO | KULMAKERROIN_PUOLI | ALAVAIHE,

	MAKI | KATTO | KULMAKERROIN_PUOLI | ALAVAIHE | MIINUS,
	MAKI | KATTO | KULMAKERROIN_PUOLI | YLAVAIHE | MIINUS,

	MAKI | KATTO | KULMAKERROIN_YKSI | YLAVAIHE,
	MAKI | KATTO | KULMAKERROIN_YKSI | MIINUS | YLAVAIHE,

	MAKI | KATTO | KULMAKERROIN_KAKSI | YLAVAIHE,
	MAKI | KATTO | KULMAKERROIN_KAKSI | ALAVAIHE,

	MAKI | KATTO | KULMAKERROIN_KAKSI | ALAVAIHE | MIINUS,
	MAKI | KATTO | KULMAKERROIN_KAKSI | YLAVAIHE | MIINUS,

	VESI,
	
	

	VESI | MAKI | KULMAKERROIN_PUOLI | ALAVAIHE | MIINUS,
	VESI | MAKI | KULMAKERROIN_PUOLI | YLAVAIHE | MIINUS,

	VESI | MAKI | KULMAKERROIN_PUOLI | YLAVAIHE,
	VESI | MAKI | KULMAKERROIN_PUOLI | ALAVAIHE,

	VESI | MAKI | KATTO | KULMAKERROIN_PUOLI | YLAVAIHE,
	VESI | MAKI | KATTO | KULMAKERROIN_PUOLI | ALAVAIHE,

	VESI | MAKI | KATTO | KULMAKERROIN_PUOLI | ALAVAIHE | MIINUS,
	VESI | MAKI | KATTO | KULMAKERROIN_PUOLI | YLAVAIHE | MIINUS,

	VASEN_BLOKKI | YLA_BLOKKI | OIKEA_BLOKKI | ALA_BLOKKI,
	KOYNNOS,
	VESI | YLA_BLOKKI,

	VESI | MAKI | KULMAKERROIN_YKSI | YLAVAIHE | MIINUS,
	VESI | MAKI | KULMAKERROIN_YKSI | YLAVAIHE, 
	 
	VESI | MAKI | KATTO | KULMAKERROIN_YKSI | YLAVAIHE,
	VESI | MAKI | KATTO | KULMAKERROIN_YKSI | MIINUS | YLAVAIHE,
};


const unsigned char kitkat[] =
{
	0,
	255,
	255,
	255,
	0,
	0,
	0,
	0,
	0,
	255,
	255,
	255,

	255,
	255,
	
	255,
	255,

	255,
	255,

	255,
	255,

	0,
	0,

	0,
	0,

	0,
	0,

	0,
	0,

	0,
	0,

	0,
	
	

	255,
	255,

	255,
	255,

	0,
	0,

	0,
	0,

	32,
	0,
	255,
	255,
	255,
	255,
	255
};
